# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1212, 685)
        self.label_top = QtWidgets.QLabel(Form)
        self.label_top.setGeometry(QtCore.QRect(10, 10, 1171, 16))
        self.label_top.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_top.setObjectName("label_top")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 1181, 621))
        self.tabWidget.setStyleSheet("background-color: rgb(228, 255, 248);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonOpenPort = QtWidgets.QPushButton(self.tab)
        self.pushButtonOpenPort.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButtonOpenPort.setObjectName("pushButtonOpenPort")
        self.pushButtonClosePort = QtWidgets.QPushButton(self.tab)
        self.pushButtonClosePort.setGeometry(QtCore.QRect(1000, 10, 91, 23))
        self.pushButtonClosePort.setObjectName("pushButtonClosePort")
        self.checkBoxPLC = QtWidgets.QCheckBox(self.tab)
        self.checkBoxPLC.setGeometry(QtCore.QRect(120, 10, 51, 20))
        self.checkBoxPLC.setChecked(True)
        self.checkBoxPLC.setObjectName("checkBoxPLC")
        self.groupBoxAxisSpeed = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisSpeed.setGeometry(QtCore.QRect(10, 40, 471, 221))
        self.groupBoxAxisSpeed.setObjectName("groupBoxAxisSpeed")
        self.label_5 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 67, 17))
        self.label_5.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_5.setObjectName("label_5")
        self.pushButtonSpeedSet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedSet.setGeometry(QtCore.QRect(243, 74, 89, 31))
        self.pushButtonSpeedSet.setObjectName("pushButtonSpeedSet")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_3.setObjectName("label_3")
        self.textEditXSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditXSpeedSet.setGeometry(QtCore.QRect(110, 23, 91, 31))
        self.textEditXSpeedSet.setObjectName("textEditXSpeedSet")
        self.pushButtonSpeedGet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedGet.setGeometry(QtCore.QRect(353, 74, 89, 31))
        self.pushButtonSpeedGet.setObjectName("pushButtonSpeedGet")
        self.label = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label.setObjectName("label")
        self.textEditZSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditZSpeedSet.setGeometry(QtCore.QRect(110, 123, 91, 31))
        self.textEditZSpeedSet.setObjectName("textEditZSpeedSet")
        self.textEditYSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditYSpeedSet.setGeometry(QtCore.QRect(110, 73, 91, 31))
        self.textEditYSpeedSet.setObjectName("textEditYSpeedSet")
        self.label_6 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.label_6.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_6.setObjectName("label_6")
        self.textEditRSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditRSpeedSet.setGeometry(QtCore.QRect(110, 173, 91, 31))
        self.textEditRSpeedSet.setObjectName("textEditRSpeedSet")
        self.groupBoxAxisLimit = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisLimit.setGeometry(QtCore.QRect(500, 40, 591, 221))
        self.groupBoxAxisLimit.setObjectName("groupBoxAxisLimit")
        self.pushButtonLimitGet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitGet.setGeometry(QtCore.QRect(470, 75, 81, 31))
        self.pushButtonLimitGet.setObjectName("pushButtonLimitGet")
        self.label_20 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_20.setGeometry(QtCore.QRect(86, 26, 251, 181))
        self.label_20.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.pushButtonLimitSet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitSet.setGeometry(QtCore.QRect(360, 75, 81, 31))
        self.pushButtonLimitSet.setObjectName("pushButtonLimitSet")
        self.label_2 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_2.setGeometry(QtCore.QRect(10, 36, 67, 17))
        self.label_2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_8.setGeometry(QtCore.QRect(10, 136, 67, 17))
        self.label_8.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_4.setGeometry(QtCore.QRect(10, 86, 67, 17))
        self.label_4.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_4.setObjectName("label_4")
        self.label_maxlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_maxlimit.setGeometry(QtCore.QRect(120, 10, 54, 20))
        self.label_maxlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_maxlimit.setObjectName("label_maxlimit")
        self.label_minlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_minlimit.setGeometry(QtCore.QRect(243, 10, 54, 20))
        self.label_minlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_minlimit.setObjectName("label_minlimit")
        self.textEditPassword = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditPassword.setGeometry(QtCore.QRect(360, 30, 81, 31))
        self.textEditPassword.setObjectName("textEditPassword")
        self.pushButtonPassword = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonPassword.setGeometry(QtCore.QRect(470, 30, 81, 31))
        self.pushButtonPassword.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.pushButtonPassword.setObjectName("pushButtonPassword")
        self.textEditXMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMaxLimit.setGeometry(QtCore.QRect(100, 36, 101, 21))
        self.textEditXMaxLimit.setObjectName("textEditXMaxLimit")
        self.textEditXMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMinLimit.setGeometry(QtCore.QRect(220, 35, 101, 21))
        self.textEditXMinLimit.setObjectName("textEditXMinLimit")
        self.textEditYMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMinLimit.setGeometry(QtCore.QRect(220, 82, 101, 21))
        self.textEditYMinLimit.setObjectName("textEditYMinLimit")
        self.textEditYMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMaxLimit.setGeometry(QtCore.QRect(100, 83, 101, 21))
        self.textEditYMaxLimit.setObjectName("textEditYMaxLimit")
        self.textEditZMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMinLimit.setGeometry(QtCore.QRect(220, 134, 101, 21))
        self.textEditZMinLimit.setObjectName("textEditZMinLimit")
        self.textEditZMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMaxLimit.setGeometry(QtCore.QRect(100, 135, 101, 21))
        self.textEditZMaxLimit.setObjectName("textEditZMaxLimit")
        self.textEditRMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditRMaxLimit.setGeometry(QtCore.QRect(100, 180, 101, 21))
        self.textEditRMaxLimit.setObjectName("textEditRMaxLimit")
        self.textEditRMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditRMinLimit.setGeometry(QtCore.QRect(220, 180, 101, 21))
        self.textEditRMinLimit.setObjectName("textEditRMinLimit")
        self.label_9 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_9.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.label_9.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBoxAxisLimit)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 120, 211, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButtonSetHomeOffset = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonSetHomeOffset.setGeometry(QtCore.QRect(110, 40, 91, 31))
        self.pushButtonSetHomeOffset.setObjectName("pushButtonSetHomeOffset")
        self.lineEditHomeOffsetValue = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditHomeOffsetValue.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.lineEditHomeOffsetValue.setObjectName("lineEditHomeOffsetValue")
        self.label_20.raise_()
        self.pushButtonLimitGet.raise_()
        self.pushButtonLimitSet.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.label_maxlimit.raise_()
        self.label_minlimit.raise_()
        self.textEditPassword.raise_()
        self.pushButtonPassword.raise_()
        self.textEditXMaxLimit.raise_()
        self.textEditXMinLimit.raise_()
        self.textEditYMinLimit.raise_()
        self.textEditYMaxLimit.raise_()
        self.textEditZMinLimit.raise_()
        self.textEditZMaxLimit.raise_()
        self.textEditRMaxLimit.raise_()
        self.textEditRMinLimit.raise_()
        self.label_9.raise_()
        self.groupBox_3.raise_()
        self.groupBoxMoveCoordiante = QtWidgets.QGroupBox(self.tab)
        self.groupBoxMoveCoordiante.setGeometry(QtCore.QRect(10, 270, 471, 191))
        self.groupBoxMoveCoordiante.setObjectName("groupBoxMoveCoordiante")
        self.textEditxMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxMove.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditxMove.setObjectName("textEditxMove")
        self.textEdityMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEdityMove.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEdityMove.setObjectName("textEdityMove")
        self.textEditzMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditzMove.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditzMove.setObjectName("textEditzMove")
        self.pushButtonMovex = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovex.setGeometry(QtCore.QRect(250, 30, 75, 19))
        self.pushButtonMovex.setObjectName("pushButtonMovex")
        self.pushButtonMovey = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovey.setGeometry(QtCore.QRect(250, 70, 75, 20))
        self.pushButtonMovey.setObjectName("pushButtonMovey")
        self.pushButtonMovez = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovez.setGeometry(QtCore.QRect(250, 110, 75, 19))
        self.pushButtonMovez.setObjectName("pushButtonMovez")
        self.pushButtonGetx = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetx.setGeometry(QtCore.QRect(350, 30, 75, 19))
        self.pushButtonGetx.setObjectName("pushButtonGetx")
        self.pushButtonGety = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGety.setGeometry(QtCore.QRect(350, 70, 75, 19))
        self.pushButtonGety.setObjectName("pushButtonGety")
        self.pushButtonGetz = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetz.setGeometry(QtCore.QRect(350, 110, 75, 19))
        self.pushButtonGetz.setObjectName("pushButtonGetz")
        self.label_10 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_10.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_11.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_14.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_14.setObjectName("label_14")
        self.pushButtonGetr = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetr.setGeometry(QtCore.QRect(350, 156, 75, 19))
        self.pushButtonGetr.setObjectName("pushButtonGetr")
        self.pushButtonMover = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMover.setGeometry(QtCore.QRect(250, 156, 75, 19))
        self.pushButtonMover.setObjectName("pushButtonMover")
        self.label_13 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_13.setGeometry(QtCore.QRect(10, 156, 67, 17))
        self.label_13.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_13.setObjectName("label_13")
        self.textEditrMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditrMove.setGeometry(QtCore.QRect(110, 150, 91, 31))
        self.textEditrMove.setObjectName("textEditrMove")
        self.groupBoxAxisStepMove = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisStepMove.setGeometry(QtCore.QRect(500, 270, 351, 191))
        self.groupBoxAxisStepMove.setObjectName("groupBoxAxisStepMove")
        self.label_12 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_12.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_15.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_16.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_16.setObjectName("label_16")
        self.pushButtonStepMoveZ = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveZ.setGeometry(QtCore.QRect(230, 109, 75, 19))
        self.pushButtonStepMoveZ.setObjectName("pushButtonStepMoveZ")
        self.textEditStepMoveX = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveX.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditStepMoveX.setObjectName("textEditStepMoveX")
        self.textEditStepMoveZ = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveZ.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditStepMoveZ.setObjectName("textEditStepMoveZ")
        self.pushButtonStepMoveY = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveY.setGeometry(QtCore.QRect(230, 69, 75, 20))
        self.pushButtonStepMoveY.setObjectName("pushButtonStepMoveY")
        self.pushButtonStepMoveX = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveX.setGeometry(QtCore.QRect(230, 29, 75, 19))
        self.pushButtonStepMoveX.setObjectName("pushButtonStepMoveX")
        self.textEditStepMoveY = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveY.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEditStepMoveY.setObjectName("textEditStepMoveY")
        self.pushButtonStepMoveR = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveR.setGeometry(QtCore.QRect(230, 149, 75, 19))
        self.pushButtonStepMoveR.setObjectName("pushButtonStepMoveR")
        self.textEditStepMoveR = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveR.setGeometry(QtCore.QRect(110, 144, 91, 31))
        self.textEditStepMoveR.setObjectName("textEditStepMoveR")
        self.label_17 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_17.setGeometry(QtCore.QRect(10, 150, 67, 17))
        self.label_17.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_17.setObjectName("label_17")
        self.pushButtonSignalReSet = QtWidgets.QPushButton(self.tab)
        self.pushButtonSignalReSet.setGeometry(QtCore.QRect(220, 10, 111, 23))
        self.pushButtonSignalReSet.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonSignalReSet.setObjectName("pushButtonSignalReSet")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 470, 211, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonLockDUT = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonLockDUT.setGeometry(QtCore.QRect(20, 40, 75, 31))
        self.pushButtonLockDUT.setObjectName("pushButtonLockDUT")
        self.pushButtonUnlockDUT = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonUnlockDUT.setGeometry(QtCore.QRect(110, 40, 91, 31))
        self.pushButtonUnlockDUT.setObjectName("pushButtonUnlockDUT")
        self.pushButtonGetPLCVer = QtWidgets.QPushButton(self.tab)
        self.pushButtonGetPLCVer.setGeometry(QtCore.QRect(380, 10, 111, 23))
        self.pushButtonGetPLCVer.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonGetPLCVer.setObjectName("pushButtonGetPLCVer")
        self.textEditPLCVer = QtWidgets.QTextEdit(self.tab)
        self.textEditPLCVer.setGeometry(QtCore.QRect(510, 10, 104, 21))
        self.textEditPLCVer.setObjectName("textEditPLCVer")
        self.groupBoxAxisStepMove_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisStepMove_2.setGeometry(QtCore.QRect(870, 270, 221, 181))
        self.groupBoxAxisStepMove_2.setObjectName("groupBoxAxisStepMove_2")
        self.pushButtonZAxisGoHome = QtWidgets.QPushButton(self.groupBoxAxisStepMove_2)
        self.pushButtonZAxisGoHome.setGeometry(QtCore.QRect(50, 110, 151, 19))
        self.pushButtonZAxisGoHome.setObjectName("pushButtonZAxisGoHome")
        self.pushButtonYAxisGoHome = QtWidgets.QPushButton(self.groupBoxAxisStepMove_2)
        self.pushButtonYAxisGoHome.setGeometry(QtCore.QRect(50, 70, 151, 20))
        self.pushButtonYAxisGoHome.setObjectName("pushButtonYAxisGoHome")
        self.pushButtonXAxisGoHome = QtWidgets.QPushButton(self.groupBoxAxisStepMove_2)
        self.pushButtonXAxisGoHome.setGeometry(QtCore.QRect(50, 30, 151, 19))
        self.pushButtonXAxisGoHome.setObjectName("pushButtonXAxisGoHome")
        self.pushButtonRAxisGoHome = QtWidgets.QPushButton(self.groupBoxAxisStepMove_2)
        self.pushButtonRAxisGoHome.setGeometry(QtCore.QRect(50, 150, 151, 19))
        self.pushButtonRAxisGoHome.setObjectName("pushButtonRAxisGoHome")
        self.pushButtonGetHolderState = QtWidgets.QPushButton(self.tab)
        self.pushButtonGetHolderState.setGeometry(QtCore.QRect(650, 10, 131, 21))
        self.pushButtonGetHolderState.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonGetHolderState.setObjectName("pushButtonGetHolderState")
        self.lineEditHolderState = QtWidgets.QLineEdit(self.tab)
        self.lineEditHolderState.setGeometry(QtCore.QRect(800, 8, 151, 25))
        self.lineEditHolderState.setObjectName("lineEditHolderState")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(250, 470, 451, 111))
        self.groupBox.setObjectName("groupBox")
        self.pushButtonSynchronousXY = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonSynchronousXY.setGeometry(QtCore.QRect(280, 30, 161, 34))
        self.pushButtonSynchronousXY.setObjectName("pushButtonSynchronousXY")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(30, 30, 67, 17))
        self.label_18.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_18.setObjectName("label_18")
        self.lineEditSynchronousXPos = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSynchronousXPos.setGeometry(QtCore.QRect(120, 30, 131, 31))
        self.lineEditSynchronousXPos.setObjectName("lineEditSynchronousXPos")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(30, 70, 67, 17))
        self.label_19.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_19.setObjectName("label_19")
        self.lineEditSynchronousYPos = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSynchronousYPos.setGeometry(QtCore.QRect(120, 70, 131, 31))
        self.lineEditSynchronousYPos.setObjectName("lineEditSynchronousYPos")
        self.groupBox.raise_()
        self.pushButtonOpenPort.raise_()
        self.pushButtonClosePort.raise_()
        self.checkBoxPLC.raise_()
        self.groupBoxAxisSpeed.raise_()
        self.groupBoxAxisLimit.raise_()
        self.groupBoxMoveCoordiante.raise_()
        self.groupBoxAxisStepMove.raise_()
        self.pushButtonSignalReSet.raise_()
        self.groupBox_2.raise_()
        self.pushButtonGetPLCVer.raise_()
        self.textEditPLCVer.raise_()
        self.groupBoxAxisStepMove_2.raise_()
        self.pushButtonGetHolderState.raise_()
        self.lineEditHolderState.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_44 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_44.setGeometry(QtCore.QRect(130, 99, 221, 111))
        self.pushButton_44.setStyleSheet("background-color: rgb(33, 255, 239);")
        self.pushButton_44.setObjectName("pushButton_44")
        self.ButtonSetXCalUp = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetXCalUp.setGeometry(QtCore.QRect(200, 59, 61, 32))
        self.ButtonSetXCalUp.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetXCalUp.setObjectName("ButtonSetXCalUp")
        self.ButtonSetZCal = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetZCal.setGeometry(QtCore.QRect(180, 170, 111, 21))
        self.ButtonSetZCal.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetZCal.setObjectName("ButtonSetZCal")
        self.ButtonSetXCalDown = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetXCalDown.setGeometry(QtCore.QRect(200, 219, 71, 32))
        self.ButtonSetXCalDown.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetXCalDown.setObjectName("ButtonSetXCalDown")
        self.ButtonSetYCalLeft = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetYCalLeft.setGeometry(QtCore.QRect(60, 129, 61, 32))
        self.ButtonSetYCalLeft.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetYCalLeft.setObjectName("ButtonSetYCalLeft")
        self.ButtonSetYCalRight = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetYCalRight.setGeometry(QtCore.QRect(360, 139, 61, 32))
        self.ButtonSetYCalRight.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetYCalRight.setObjectName("ButtonSetYCalRight")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 300, 871, 281))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 30, 831, 61))
        self.groupBox_6.setObjectName("groupBox_6")
        self.splitter = QtWidgets.QSplitter(self.groupBox_6)
        self.splitter.setGeometry(QtCore.QRect(20, 30, 801, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButtonCap6mm_V = QtWidgets.QRadioButton(self.splitter)
        self.radioButtonCap6mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCap6mm_V.setObjectName("radioButtonCap6mm_V")
        self.radioButtonCap7mm_V = QtWidgets.QRadioButton(self.splitter)
        self.radioButtonCap7mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCap7mm_V.setObjectName("radioButtonCap7mm_V")
        self.radioButtonCap9mm_V = QtWidgets.QRadioButton(self.splitter)
        self.radioButtonCap9mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCap9mm_V.setObjectName("radioButtonCap9mm_V")
        self.radioButtonCap12mm_V = QtWidgets.QRadioButton(self.splitter)
        self.radioButtonCap12mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCap12mm_V.setObjectName("radioButtonCap12mm_V")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 160, 831, 61))
        self.groupBox_7.setObjectName("groupBox_7")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_7)
        self.splitter_2.setGeometry(QtCore.QRect(20, 30, 801, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.radioButtonCalDistance10mm_V = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButtonCalDistance10mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCalDistance10mm_V.setObjectName("radioButtonCalDistance10mm_V")
        self.radioButtonCalDistance12mm_V = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButtonCalDistance12mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCalDistance12mm_V.setObjectName("radioButtonCalDistance12mm_V")
        self.radioButtonCalDistance135mm_V = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButtonCalDistance135mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCalDistance135mm_V.setObjectName("radioButtonCalDistance135mm_V")
        self.radioButtonCalDistance15mm_V = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButtonCalDistance15mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCalDistance15mm_V.setObjectName("radioButtonCalDistance15mm_V")
        self.radioButtonCalDistance20mm_V = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButtonCalDistance20mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCalDistance20mm_V.setObjectName("radioButtonCalDistance20mm_V")
        self.radioButtonCalDistance30mm_V = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButtonCalDistance30mm_V.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonCalDistance30mm_V.setObjectName("radioButtonCalDistance30mm_V")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 90, 831, 61))
        self.groupBox_9.setObjectName("groupBox_9")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox_9)
        self.splitter_3.setGeometry(QtCore.QRect(20, 30, 801, 23))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.radioButtonHorizontalBack = QtWidgets.QRadioButton(self.splitter_3)
        self.radioButtonHorizontalBack.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonHorizontalBack.setObjectName("radioButtonHorizontalBack")
        self.radioButtonHorizontalFront = QtWidgets.QRadioButton(self.splitter_3)
        self.radioButtonHorizontalFront.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonHorizontalFront.setObjectName("radioButtonHorizontalFront")
        self.radioButtonVerticalRight = QtWidgets.QRadioButton(self.splitter_3)
        self.radioButtonVerticalRight.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonVerticalRight.setObjectName("radioButtonVerticalRight")
        self.radioButtonVerticalLeft = QtWidgets.QRadioButton(self.splitter_3)
        self.radioButtonVerticalLeft.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonVerticalLeft.setObjectName("radioButtonVerticalLeft")
        self.ButtonStartCal = QtWidgets.QPushButton(self.groupBox_5)
        self.ButtonStartCal.setGeometry(QtCore.QRect(170, 230, 171, 41))
        self.ButtonStartCal.setStyleSheet("background-color: rgb(41, 255, 229);")
        self.ButtonStartCal.setObjectName("ButtonStartCal")
        self.ButtonMoveToCalibrationPosition = QtWidgets.QPushButton(self.groupBox_5)
        self.ButtonMoveToCalibrationPosition.setGeometry(QtCore.QRect(510, 230, 211, 41))
        self.ButtonMoveToCalibrationPosition.setStyleSheet("background-color: rgb(41, 255, 229);")
        self.ButtonMoveToCalibrationPosition.setObjectName("ButtonMoveToCalibrationPosition")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_17.setGeometry(QtCore.QRect(900, 310, 271, 131))
        self.groupBox_17.setObjectName("groupBox_17")
        self.pushButtonCapVerticalLeftUp = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButtonCapVerticalLeftUp.setGeometry(QtCore.QRect(20, 30, 101, 31))
        self.pushButtonCapVerticalLeftUp.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.pushButtonCapVerticalLeftUp.setObjectName("pushButtonCapVerticalLeftUp")
        self.pushButtonCapVerticalRightDown = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButtonCapVerticalRightDown.setGeometry(QtCore.QRect(150, 80, 101, 31))
        self.pushButtonCapVerticalRightDown.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.pushButtonCapVerticalRightDown.setObjectName("pushButtonCapVerticalRightDown")
        self.pushButtonCapVerticalLeftDowm = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButtonCapVerticalLeftDowm.setGeometry(QtCore.QRect(140, 30, 111, 31))
        self.pushButtonCapVerticalLeftDowm.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.pushButtonCapVerticalLeftDowm.setObjectName("pushButtonCapVerticalLeftDowm")
        self.pushButtonCapVerticalRightUp = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButtonCapVerticalRightUp.setGeometry(QtCore.QRect(20, 80, 101, 31))
        self.pushButtonCapVerticalRightUp.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.pushButtonCapVerticalRightUp.setObjectName("pushButtonCapVerticalRightUp")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_18.setGeometry(QtCore.QRect(20, 10, 1141, 281))
        self.groupBox_18.setObjectName("groupBox_18")
        self.ButtonBurninStart = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonBurninStart.setGeometry(QtCore.QRect(910, 90, 121, 32))
        self.ButtonBurninStart.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonBurninStart.setObjectName("ButtonBurninStart")
        self.ButtonCurtainOFF = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonCurtainOFF.setGeometry(QtCore.QRect(720, 140, 121, 32))
        self.ButtonCurtainOFF.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCurtainOFF.setObjectName("ButtonCurtainOFF")
        self.textEditOffset = QtWidgets.QTextEdit(self.groupBox_18)
        self.textEditOffset.setGeometry(QtCore.QRect(800, 20, 121, 41))
        self.textEditOffset.setObjectName("textEditOffset")
        self.ButtonLEDControl = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonLEDControl.setGeometry(QtCore.QRect(510, 190, 121, 32))
        self.ButtonLEDControl.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonLEDControl.setObjectName("ButtonLEDControl")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_18)
        self.comboBox.setGeometry(QtCore.QRect(720, 240, 121, 31))
        self.comboBox.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.ButtonRunPattern = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonRunPattern.setGeometry(QtCore.QRect(720, 190, 121, 32))
        self.ButtonRunPattern.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonRunPattern.setObjectName("ButtonRunPattern")
        self.label_38 = QtWidgets.QLabel(self.groupBox_18)
        self.label_38.setGeometry(QtCore.QRect(720, 20, 71, 41))
        self.label_38.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.ButtonCylinderIn = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonCylinderIn.setGeometry(QtCore.QRect(510, 140, 121, 32))
        self.ButtonCylinderIn.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCylinderIn.setObjectName("ButtonCylinderIn")
        self.ButtonCylinderOut = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonCylinderOut.setGeometry(QtCore.QRect(510, 90, 121, 32))
        self.ButtonCylinderOut.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCylinderOut.setObjectName("ButtonCylinderOut")
        self.ButtonCurtainON = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonCurtainON.setGeometry(QtCore.QRect(720, 90, 121, 32))
        self.ButtonCurtainON.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCurtainON.setObjectName("ButtonCurtainON")
        self.textEditBurninTimes = QtWidgets.QTextEdit(self.groupBox_18)
        self.textEditBurninTimes.setGeometry(QtCore.QRect(910, 140, 121, 31))
        self.textEditBurninTimes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditBurninTimes.setObjectName("textEditBurninTimes")
        self.comboBoxLED = QtWidgets.QComboBox(self.groupBox_18)
        self.comboBoxLED.setGeometry(QtCore.QRect(510, 240, 121, 31))
        self.comboBoxLED.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.comboBoxLED.setObjectName("comboBoxLED")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.ButtonCalZAxisHeight = QtWidgets.QPushButton(self.groupBox_18)
        self.ButtonCalZAxisHeight.setGeometry(QtCore.QRect(910, 190, 121, 32))
        self.ButtonCalZAxisHeight.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCalZAxisHeight.setObjectName("ButtonCalZAxisHeight")
        self.groupBox_18.raise_()
        self.groupBox_17.raise_()
        self.pushButton_44.raise_()
        self.ButtonSetXCalUp.raise_()
        self.ButtonSetZCal.raise_()
        self.ButtonSetXCalDown.raise_()
        self.ButtonSetYCalLeft.raise_()
        self.ButtonSetYCalRight.raise_()
        self.groupBox_5.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.label_bottom = QtWidgets.QLabel(Form)
        self.label_bottom.setGeometry(QtCore.QRect(10, 660, 1171, 20))
        self.label_bottom.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bottom.setObjectName("label_bottom")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BojayMultiFingerTouch"))
        self.label_top.setText(_translate("Form", "Bojay Multi Finger Touch UI V1.0"))
        self.pushButtonOpenPort.setText(_translate("Form", "OpenPort"))
        self.pushButtonClosePort.setText(_translate("Form", "ClosePort"))
        self.checkBoxPLC.setText(_translate("Form", "PLC"))
        self.groupBoxAxisSpeed.setTitle(_translate("Form", "Axis Speed"))
        self.label_5.setText(_translate("Form", "Z Axis"))
        self.pushButtonSpeedSet.setText(_translate("Form", "Set"))
        self.label_3.setText(_translate("Form", "Y Axis"))
        self.pushButtonSpeedGet.setText(_translate("Form", "Get"))
        self.label.setText(_translate("Form", "X Axis"))
        self.label_6.setText(_translate("Form", "R Axis"))
        self.groupBoxAxisLimit.setTitle(_translate("Form", "Axis Limit"))
        self.pushButtonLimitGet.setText(_translate("Form", "Get"))
        self.pushButtonLimitSet.setText(_translate("Form", "Set"))
        self.label_2.setText(_translate("Form", "X Axis"))
        self.label_8.setText(_translate("Form", "Z Axis"))
        self.label_4.setText(_translate("Form", "Y Axis"))
        self.label_maxlimit.setText(_translate("Form", "MaxLimit"))
        self.label_minlimit.setText(_translate("Form", "MinLimit"))
        self.pushButtonPassword.setText(_translate("Form", "Password"))
        self.label_9.setText(_translate("Form", "R Axis"))
        self.groupBox_3.setTitle(_translate("Form", "SetHomeOffset"))
        self.pushButtonSetHomeOffset.setText(_translate("Form", "Set"))
        self.groupBoxMoveCoordiante.setTitle(_translate("Form", "Move Coordinate"))
        self.pushButtonMovex.setText(_translate("Form", "Move X"))
        self.pushButtonMovey.setText(_translate("Form", "Move Y"))
        self.pushButtonMovez.setText(_translate("Form", "Move Z"))
        self.pushButtonGetx.setText(_translate("Form", "Get X"))
        self.pushButtonGety.setText(_translate("Form", "Get Y"))
        self.pushButtonGetz.setText(_translate("Form", "Get Z"))
        self.label_10.setText(_translate("Form", "X Axis"))
        self.label_11.setText(_translate("Form", "Z Axis"))
        self.label_14.setText(_translate("Form", "Y Axis"))
        self.pushButtonGetr.setText(_translate("Form", "Get R"))
        self.pushButtonMover.setText(_translate("Form", "Move R"))
        self.label_13.setText(_translate("Form", "R Axis"))
        self.groupBoxAxisStepMove.setTitle(_translate("Form", "Set step"))
        self.label_12.setText(_translate("Form", "X Axis"))
        self.label_15.setText(_translate("Form", "Y Axis"))
        self.label_16.setText(_translate("Form", "Z Axis"))
        self.pushButtonStepMoveZ.setText(_translate("Form", "Move Z"))
        self.pushButtonStepMoveY.setText(_translate("Form", "Move Y"))
        self.pushButtonStepMoveX.setText(_translate("Form", "Move X"))
        self.pushButtonStepMoveR.setText(_translate("Form", "Move R"))
        self.label_17.setText(_translate("Form", "R Axis"))
        self.pushButtonSignalReSet.setText(_translate("Form", "SignalReSet"))
        self.groupBox_2.setTitle(_translate("Form", "DUT"))
        self.pushButtonLockDUT.setText(_translate("Form", "LockDUT"))
        self.pushButtonUnlockDUT.setText(_translate("Form", "UnlockDUT"))
        self.pushButtonGetPLCVer.setText(_translate("Form", "ReadPCLVer"))
        self.groupBoxAxisStepMove_2.setTitle(_translate("Form", "GoHome"))
        self.pushButtonZAxisGoHome.setText(_translate("Form", "ZAxisGoHome"))
        self.pushButtonYAxisGoHome.setText(_translate("Form", "YAxisGoHome"))
        self.pushButtonXAxisGoHome.setText(_translate("Form", " XAxisGoHome"))
        self.pushButtonRAxisGoHome.setText(_translate("Form", "RAxisGoHome"))
        self.pushButtonGetHolderState.setText(_translate("Form", "GetHolderSate"))
        self.groupBox.setTitle(_translate("Form", "Synchronous"))
        self.pushButtonSynchronousXY.setText(_translate("Form", "SynchronousXY"))
        self.label_18.setText(_translate("Form", "X Axis"))
        self.label_19.setText(_translate("Form", "Y Axis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "PLC"))
        self.pushButton_44.setText(_translate("Form", "I am calibration KIT"))
        self.ButtonSetXCalUp.setText(_translate("Form", "Set Up"))
        self.ButtonSetZCal.setText(_translate("Form", "Set Z "))
        self.ButtonSetXCalDown.setText(_translate("Form", "Set down"))
        self.ButtonSetYCalLeft.setText(_translate("Form", "Set Left"))
        self.ButtonSetYCalRight.setText(_translate("Form", "Set Right"))
        self.groupBox_5.setTitle(_translate("Form", "画线校准选择"))
        self.groupBox_6.setTitle(_translate("Form", "电容笔头直径选择："))
        self.radioButtonCap6mm_V.setText(_translate("Form", "D6mm"))
        self.radioButtonCap7mm_V.setText(_translate("Form", "D7mm"))
        self.radioButtonCap9mm_V.setText(_translate("Form", "D9mm"))
        self.radioButtonCap12mm_V.setText(_translate("Form", "D12mm"))
        self.groupBox_7.setTitle(_translate("Form", "校准距离选择："))
        self.radioButtonCalDistance10mm_V.setText(_translate("Form", "L10mm"))
        self.radioButtonCalDistance12mm_V.setText(_translate("Form", "L12mm"))
        self.radioButtonCalDistance135mm_V.setText(_translate("Form", "L13.5mm"))
        self.radioButtonCalDistance15mm_V.setText(_translate("Form", "L15mm"))
        self.radioButtonCalDistance20mm_V.setText(_translate("Form", "L20mm"))
        self.radioButtonCalDistance30mm_V.setText(_translate("Form", "L30mm"))
        self.groupBox_9.setTitle(_translate("Form", "电容笔头选择："))
        self.radioButtonHorizontalBack.setText(_translate("Form", "A笔头"))
        self.radioButtonHorizontalFront.setText(_translate("Form", "B笔头"))
        self.radioButtonVerticalRight.setText(_translate("Form", "C笔头"))
        self.radioButtonVerticalLeft.setText(_translate("Form", "D笔头"))
        self.ButtonStartCal.setText(_translate("Form", "Start Calibration"))
        self.ButtonMoveToCalibrationPosition.setText(_translate("Form", "Move to Calibration Position"))
        self.groupBox_17.setTitle(_translate("Form", "笔头动作"))
        self.pushButtonCapVerticalLeftUp.setText(_translate("Form", "A气缸上"))
        self.pushButtonCapVerticalRightDown.setText(_translate("Form", "B气缸下"))
        self.pushButtonCapVerticalLeftDowm.setText(_translate("Form", "A气缸下"))
        self.pushButtonCapVerticalRightUp.setText(_translate("Form", "B气缸上"))
        self.groupBox_18.setTitle(_translate("Form", "校准"))
        self.ButtonBurninStart.setText(_translate("Form", "BurninStart"))
        self.ButtonCurtainOFF.setText(_translate("Form", "LightCurtainOFF"))
        self.ButtonLEDControl.setText(_translate("Form", "LEDControl"))
        self.comboBox.setItemText(0, _translate("Form", "Rectangle"))
        self.comboBox.setItemText(1, _translate("Form", "Circle/EIIipse"))
        self.ButtonRunPattern.setText(_translate("Form", "RunPattern"))
        self.label_38.setText(_translate("Form", "Offset"))
        self.ButtonCylinderIn.setText(_translate("Form", "Cylinder in"))
        self.ButtonCylinderOut.setText(_translate("Form", "Cylinder out"))
        self.ButtonCurtainON.setText(_translate("Form", "LightCurtainON"))
        self.comboBoxLED.setItemText(0, _translate("Form", "1-red-on"))
        self.comboBoxLED.setItemText(1, _translate("Form", "1-red-off"))
        self.comboBoxLED.setItemText(2, _translate("Form", "1-yellow-on"))
        self.comboBoxLED.setItemText(3, _translate("Form", "1-yellow-off"))
        self.comboBoxLED.setItemText(4, _translate("Form", "1-green-on"))
        self.comboBoxLED.setItemText(5, _translate("Form", "1-green-off"))
        self.comboBoxLED.setItemText(6, _translate("Form", "2-red-on"))
        self.comboBoxLED.setItemText(7, _translate("Form", "2-red-off"))
        self.comboBoxLED.setItemText(8, _translate("Form", "2-green-on"))
        self.comboBoxLED.setItemText(9, _translate("Form", "2-green-off"))
        self.comboBoxLED.setItemText(10, _translate("Form", "2-yellow-on"))
        self.comboBoxLED.setItemText(11, _translate("Form", "2-yellow-off"))
        self.ButtonCalZAxisHeight.setText(_translate("Form", "CalZAxisHeight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Cal"))
        self.label_bottom.setText(_translate("Form", "Developed by Bojay"))
